### ISSUE TITLE
Loading SDLPoP.ini causes a crash

### ISSUE THREAD

**Issue by Ryzee119** [Ryzee119/SDLPoPX#1]
Just needs some debugging in

https://github.com/Ryzee119/SDLPoPX/blob/77ca206da4e9176d790122d7fba625f3470757ba/src/menu.c#L2074

Fix is to not have `SDLPoP.ini` in the root directory, and it will load default settings instead. The Makefile does not copy `SDLPoP.ini` for this reason at this stage.

**Comment by Ryzee119** [comment]
Narrow it down to this section:
https://github.com/Ryzee119/SDLPoPX/blob/77ca206da4e9176d790122d7fba625f3470757ba/src/options.c#L58-L71

feof() never returns true, and also it seems to corrupt memory. If you break of the while loop it crashes at `return 0`

**Comment by JayFoxRox** [comment]
Known nxdk bug in OpenXDK backend for pdclib `feof`. See https://github.com/XboxDev/nxdk-pdclib/pull/22#issuecomment-579080073.

Will be fixed by https://github.com/XboxDev/nxdk-pdclib/pull/15; but all paths will have to be absolute (and use backslashes) then - which likely causes more issues for your codebase.

**Comment by Ryzee119** [comment]
Thanks @JayFoxRox!
I will keep that in mind regarding the absolute paths, iIll likely just update all the fileio accordingly soon.

**Comment by Ryzee119** [comment]
SDLPoP.ini file is no longer used, and seemed fairly redundant. I use SDLPoP.cfg which is now saved and loaded from E:\UDATA\.. using standard xbox save profiles. All settings adjustable in game.

This issue is effectively moot.
